agent {
    data_dir = "/opt/spire/data/agent"
    log_level = "INFO"
    log_file = "/dev/stdout"
    server_address = "spire-server"
    server_port = "8081"
    socket_path = "/run/spire/sockets/agent.sock"
    trust_domain = "partner.example.com"
    insecure_bootstrap = true
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            directory = "/opt/spire/data/agent"
        }
    }

    # Use unix attestor (processes in same container)
    WorkloadAttestor "unix" {
        plugin_data {}
    }
}

health_checks {
    listener_enabled = true
    bind_address = "127.0.0.1"
    bind_port = "8089"
    live_path = "/live"
    ready_path = "/ready"
}
